name: Chat CI/CD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
            pip install poetry
            make install
        - name: Check Lint
          run: make lint
        - name: Run Tests
          env:
            APP_REDIS_URL: ${{ secrets.APP_REDIS_URL }}
            APP_REDIS_TEST_URL: ${{ secrets.APP_REDIS_TEST_URL }}
          run: make test